[package]
name = "qcc"
version = "0.1.0"
authors = ["斎藤基樹 <stmtk13044032@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
